import { Resend } from 'resend';
import { NextResponse } from 'next/server';

interface QuoteRequest {
  platform: string;
  projectType: string;
  pages: string[];
  features: string[];
  design: string;
  priceMin: string;
  priceMax: string;
  // Contact info
  name?: string;
  email?: string;
  phone?: string;
  notes?: string;
}

export async function POST(request: Request) {
  try {
    // Check if API key is configured
    if (!process.env.RESEND_API_KEY) {
      console.error('RESEND_API_KEY is not configured');
      return NextResponse.json(
        { error: 'Email service not configured' },
        { status: 500 }
      );
    }

    const resend = new Resend(process.env.RESEND_API_KEY);
    const body: QuoteRequest = await request.json();
    const { platform, projectType, pages, features, design, priceMin, priceMax, name, email, phone, notes } = body;

    // Validate required fields
    if (!platform || !projectType) {
      return NextResponse.json(
        { error: 'Platform and project type are required' },
        { status: 400 }
      );
    }

    const pagesHtml = pages.length > 0
      ? pages.map(p => `<li>${p}</li>`).join('')
      : '<li>None selected</li>';

    const featuresHtml = features.length > 0
      ? features.map(f => `<li>${f}</li>`).join('')
      : '<li>None selected</li>';

    const { data, error } = await resend.emails.send({
      from: 'MOTOGNA Tech Studio <noreply@motogna.tech>',
      to: ['alex@motogna.tech'],
      replyTo: email || undefined,
      subject: `Quote Request: ${projectType} - ${platform} (${priceMin} - ${priceMax})`,
      html: `
        <h2>New Quote Request</h2>

        ${name || email || phone ? `
        <div style="background: #f5f5f5; padding: 15px; margin-bottom: 20px;">
          <h3 style="margin: 0 0 10px 0;">Contact Information</h3>
          ${name ? `<p style="margin: 5px 0;"><strong>Name:</strong> ${name}</p>` : ''}
          ${email ? `<p style="margin: 5px 0;"><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>` : ''}
          ${phone ? `<p style="margin: 5px 0;"><strong>Phone:</strong> <a href="tel:${phone}">${phone}</a></p>` : ''}
        </div>
        ` : ''}

        <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
          <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee; font-weight: bold; width: 150px;">Platform:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">${platform}</td>
          </tr>
          <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee; font-weight: bold;">Project Type:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">${projectType}</td>
          </tr>
          <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee; font-weight: bold; vertical-align: top;">Pages:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">
              <ul style="margin: 0; padding-left: 20px;">${pagesHtml}</ul>
            </td>
          </tr>
          <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee; font-weight: bold; vertical-align: top;">Features:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">
              <ul style="margin: 0; padding-left: 20px;">${featuresHtml}</ul>
            </td>
          </tr>
          <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee; font-weight: bold;">Design:</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">${design}</td>
          </tr>
          <tr style="background: #f9f9f9;">
            <td style="padding: 15px; font-weight: bold; font-size: 16px;">Estimated Price:</td>
            <td style="padding: 15px; font-size: 18px; font-weight: bold; color: #333;">${priceMin} – ${priceMax}</td>
          </tr>
        </table>

        ${notes ? `
        <div style="margin-top: 20px; padding: 15px; background: #f5f5f5;">
          <h3 style="margin: 0 0 10px 0;">Additional Notes</h3>
          <p style="margin: 0;">${notes.replace(/\n/g, '<br>')}</p>
        </div>
        ` : ''}

        <hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;">
        <p style="color: #666; font-size: 12px;">Generated by MOTOGNA Tech Studio Project Configurator</p>
      `,
    });

    if (error) {
      console.error('Resend error:', error);
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
    }

    return NextResponse.json({ success: true, id: data?.id });
  } catch (error) {
    console.error('Server error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
